### ISSUE TITLE
dcism-osc dependency

### ISSUE THREAD

**Issue by YagiBear** [randomnord/idracUbuntu20.04#1]
Thank you for creating this! I get an error once I try to install the idrac software that there is a dcism-osc dependency, however I cannot install dcism-osc on ubuntu 20.04. How did you get the install to work?

Thanks!

**Comment by dhaugli** [comment]
I got the same error.

**Comment by jimy-chinn** [comment]
Sorry for the late reply, i didnt get the notification.

I didnt have that error when i ran the script. Did you use this specific package?

OM-iSM-Dell-Web-LX-350-1862_A00

**Comment by crishoj** [comment]
Add this apt source:

```
deb https://linux.dell.com/repo/community/openmanage/iSM/4200/focal focal main
```

Then, both `dcism` and `dcism-osc` can be installed with `apt`.

**Comment by jimy-chinn** [comment]
> Add this apt source:
> 
> ```
> deb https://linux.dell.com/repo/community/openmanage/iSM/4200/focal focal main
> ```
> 
> Then, both `dcism` and `dcism-osc` can be installed with `apt`.

Closing as @crishoj has answered
